apiVersion: v1
kind: Pod
metadata:
  name: receiver
  namespace: messaging
spec:
  containers:
    - name: receiver
      image: python:3.10
      command: ["sh", "-c"]
      args:
        - |
          pip install pika && \
          python -c "
          import pika
          def callback(ch, method, properties, body):
              print('Mensaje recibido:', body.decode())
          conn = pika.BlockingConnection(pika.ConnectionParameters(host='rabbitmq.messaging.svc.cluster.local', credentials=pika.PlainCredentials('user', 'bitnami')))
          ch = conn.channel()
          ch.queue_declare(queue='test')
          ch.basic_consume(queue='test', on_message_callback=callback, auto_ack=True)
          print('Esperando mensajes...')
          ch.start_consuming()
          "
