apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-persistent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-persistent
  template:
    metadata:
      labels:
        app: nginx-persistent
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: contenido
      volumes:
      - name: contenido
        persistentVolumeClaim:
          claimName: nginx-pvc
