logstashConfig:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]

  pipelines.yml: |
    - pipeline.id: simple-pipeline
      path.config: "/usr/share/logstash/pipeline/logstash.conf"

pipeline:
  logstash.conf: |
    input {
      stdin { }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "prueba-logs"
      }
      stdout { codec => rubydebug }
    }

serviceMonitor:
  enabled: true

metrics:
  enabled: true
