apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod1
  name: pod1
  namespace: roles
spec:
  serviceAccountName: build-robot
  containers:
  - image: bitnami/kubectl:latest
    name: pod1
    command: ["sleep","3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}