apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
  namespace: multicontainer
spec:
  containers:
  - image: nginx
    name: container1
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
  - name: container2
    image: busybox 
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
    command: ["sh", "-c", "while true; do echo 'prueba'; ls /var/log/nginx ; sleep 5; done" ]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
   - name: logs
     emptyDir: {}
status: {}