apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventas-deploy
  namespace: servicios
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: ventas
    spec:
     containers:
      - image: nginx
        name: pod1
