apiVersion: v1
kind: Pod
metadata:
  namespace: servicios
  name: bastion
spec:
  containers:
  - image: busybox
    name: container1
    command: ["sh" , "-c", "sleep 3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}