apiVersion: v1
kind: Pod
metadata:
  namespace: servicios
  labels:
    app.kubernetes.io/name: ventas
  name: pod1
spec:
  containers:
  - image: nginx
    name: pod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}