apiVersion: v1
kind: Service
metadata:
  name: servicio-ventas
  namespace: servicios
spec:
  selector:
    app.kubernetes.io/name: ventas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
