apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Puerto interno del servicio
      targetPort: 80  # Puerto del contenedor NGINX
  type: ClusterIP     # Puedes cambiar a LoadBalancer o NodePort si quieres acceso externo
